"""Locked discretisation and architecture constants."""

from __future__ import annotations

import math

NUM_SPATIAL_DIMS = 2
DOMAIN_EXTENT = 2.0 * math.pi
DNS_NUM_POINTS = 256
COARSE_NUM_POINTS = 64
COARSENING_FACTOR = DNS_NUM_POINTS // COARSE_NUM_POINTS
COARSE_DT = 1.0e-2
DEFAULT_DIFFUSIVITY = 1.0e-3
ETDRK_ORDER = 2

CLOSURE_IN_CHANNELS = 1
CLOSURE_OUT_CHANNELS = 1
CLOSURE_HIDDEN_CHANNELS = 64
CLOSURE_DEPTH = 10
CLOSURE_KERNEL_SIZE = 5
CLOSURE_SEED = 0

INITIAL_CONDITION_MIN_MODE = 10
INITIAL_CONDITION_MAX_MODE = 32
TRAIN_SEED_RANGE = range(0, 10_000)
VALIDATION_SEED_RANGE = range(10_000, 10_032)
TEST_SEED_RANGE = range(20_000, 20_032)
UNROLL_CURRICULUM = (1, 5, 30)
LEARNING_RATE = 1.0e-4
STATIC_SMAGORINSKY_COEFFICIENT = 0.17
SMAGORINSKY_TEST_FILTER_RATIO = 2
